@startuml
'https://plantuml.com/sequence-diagram

autonumber

[->GameController:Start
GameController -> Player:Create 2-4
Player -> Die:Create 1
loop gameActive=true
    Player -> Die:Roll

    alt Pay Rent
        Player -> Player:Pay other player
    else Buy field
        Player -> Bank:Give money
        Bank -> Player:Give plot
    else Chance Card
        Player -> Chance:Draw Card
        Chance -> Player:Stuff happens
    else Go to Jail
        Player -> Player:Go to Jail
    end
end
Player -> GameController:Win Message

@enduml