@startuml
'https://plantuml.com/sequence-diagram

autonumber

[->GameController:Start
GameController -> Player:Create 2-4
Player -> Die:Create
loop gameActive=true
    Player -> Die:rollDie()

    alt Pay Rent
        Player -> Player:Pay other player - changeBalance()
    else Buy field
        Player -> Bank:changeBalance()
        Bank -> Player:claimPlot()
    else Chance Card
        Player -> Chance:drawCard()
        Chance -> Player:Stuff happens
    else Go to Jail
        Player -> Player:setInJail()
    end
end
Player -> GameController:Win Message

@enduml